#!/bin/bash
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${GREEN}[+]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[x]${NC} $1"; }
info() { echo -e "${CYAN}[*]${NC} $1"; }

if [ "$(id -u)" -ne 0 ]; then
    err "This script must be run as root (use sudo)."
    exit 1
fi

INSTALL_DIR="/home/pi/mp3player"
if [ "$(pwd)" != "$INSTALL_DIR" ] && [ "$(pwd)" != "/home/pi/tailsmusicv2" ]; then
    warn "You are in: $(pwd)"
    warn "TailsMusic expects to run from: $INSTALL_DIR"
    echo ""
    read -rp "Clone/install to $INSTALL_DIR? [Y/n]: " yn
    yn=${yn:-Y}
    if [[ "$yn" =~ ^[Yy]$ ]]; then
        if [ ! -d "$INSTALL_DIR" ]; then
            log "Creating $INSTALL_DIR"
            mkdir -p "$INSTALL_DIR"
        fi
        if [ "$(pwd)" != "$INSTALL_DIR" ]; then
            log "Copying files to $INSTALL_DIR"
            rsync -a --exclude='.git' --exclude='songs' --exclude='playlists' . /home/pi/tailsmusicv2/ 2>/dev/null || cp -r ./* "$INSTALL_DIR/" 2>/dev/null || true
            cd "$INSTALL_DIR"
        fi
    else
        INSTALL_DIR="$(pwd)"
        log "Using current directory: $INSTALL_DIR"
    fi
fi

log "Updating package lists..."
apt update

log "Installing system dependencies..."
apt install -y \
    pulseaudio pulseaudio-module-bluetooth \
    espeak-ng \
    evtest python3-evdev \
    network-manager \
    hostapd dnsmasq \
    python3-pip python3-pygame

log "Installing Python packages..."
pip3 install --break-system-packages evdev 2>/dev/null || true
pip3 install --break-system-packages pygame 2>/dev/null || true
pip3 install --break-system-packages pulsectl bleak 2>/dev/null || true

log "Creating directory structure..."
mkdir -p "$INSTALL_DIR/songs" "$INSTALL_DIR/playlists"
chown -R pi:pi "$INSTALL_DIR" 2>/dev/null || true

CONFIG_FILE="$INSTALL_DIR/config.json"
if [ ! -f "$CONFIG_FILE" ]; then
    log "Generating default config.json..."
    cat > "$CONFIG_FILE" << 'EOF'
{
    "okbutton": "KEY_PLAYCD",
    "okbutton2": "KEY_PAUSECD",
    "backbutton": "KEY_PREVIOUSSONG",
    "skipbutton": "KEY_NEXTSONG",
    "evtestname": "SIMOLIO"
}
EOF
    warn "config.json created with defaults for SIMOLIO headphones."
    warn "Run 'sudo evtest' to find your button codes and edit config.json."
else
    log "config.json already exists, skipping."
fi

info ""
info "--- Bluetooth Pairing Guide ---"
info "Put your headphones in pairing mode, then run:"
echo ""
echo "  sudo bluetoothctl scan on"
echo "  # Find your device MAC (e.g., AA:BB:CC:DD:EE:FF)"
echo "  sudo bluetoothctl pair AA:BB:CC:DD:EE:FF"
echo "  sudo bluetoothctl trust AA:BB:CC:DD:EE:FF"
echo "  sudo bluetoothctl connect AA:BB:CC:DD:EE:FF"
echo ""

read -rp "Have you paired your headphones? [y/N]: " paired
if [[ "$paired" =~ ^[Yy]$ ]]; then
    read -rp "Enter your headphones MAC address (e.g., AA:BB:CC:DD:EE:FF): " mac
    mac=$(echo "$mac" | tr 'a-z' 'A-Z')
    BT_MAC="$mac"
    SINK_NAME="bluez_sink.${mac//:/_}.a2dp_sink"
    SINK_HF="bluez_sink.${mac//:/_}.handsfree_head_unit"

    log "Updating bashrc for auto-connect..."
    cat > /home/pi/.bashrc << BASHRC
# TailsMusic - Auto-generated by setup.sh
case \$- in *i*) ;; *) return;; esac
HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000
shopt -s checkwinsize
force_color_prompt=yes
if [ -n "\$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        color_prompt=yes
    else
        color_prompt=
    fi
fi
if [ "\$color_prompt" = yes ]; then
    PS1='\${debian_chroot:+(\$debian_chroot)}\\\[\033[01;32m\\\]\\u@\\h\\\[\033[00m\\\]:\\\[\033[01;34m\\\]\\w \\\$\\\[\033[00m\\\] '
else
    PS1='\${debian_chroot:+(\$debian_chroot)}\\\u@\\h:\\w\\\$ '
fi
unset color_prompt force_color_prompt
case "\$TERM" in xterm*|rxvt*) PS1="\\\[\e]0;\${debian_chroot:+(\$debian_chroot)}\u@\h: \w\a\\\]\$PS1" ;; *) ;; esac
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "\$(dircolors -b ~/.dircolors)" || eval "\$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
fi
echo "Press Ctrl-C now to enter terminal"
echo "Waiting 2 seconds"
sleep 2
while true; do
    echo "Starting pulseaudio"
    pulseaudio --start 2>/dev/null || true
    sleep 1
    echo "Connecting to Bluetooth: $BT_MAC"
    sudo bluetoothctl connect $BT_MAC
    while [ "\$?" != "0" ]; do
        echo "Retrying Bluetooth connection..."
        pulseaudio --kill 2>/dev/null || true
        sleep 1
        pulseaudio --start 2>/dev/null || true
        sleep 1
        sudo bluetoothctl connect $BT_MAC
    done
    sleep 1
    echo "Setting default audio sink"
    pactl set-default-sink $SINK_NAME 2>/dev/null || true
    pactl set-default-sink $SINK_HF 2>/dev/null || true
    echo "Starting TailsMusic"
    cd $INSTALL_DIR
    python3 player.py
    cd
done
BASHRC
    chown pi:pi /home/pi/.bashrc
    log "bashrc written. Bluetooth will auto-connect on login."
else
    warn "Skipping Bluetooth auto-connect setup."
    warn "You can manually pair later and update /home/pi/.bashrc with the MAC."
fi

info ""
info "--- Systemd Service (auto-start on boot) ---"
read -rp "Create systemd service to auto-start TailsMusic on boot? [Y/n]: " svc
svc=${svc:-Y}
if [[ "$svc" =~ ^[Yy]$ ]]; then
    cat > /etc/systemd/system/tailsmusic.service << SERVICE
[Unit]
Description=TailsMusic MP3 Player
After=network.target sound.target bluetooth.target
Wants=bluetooth.target

[Service]
Type=simple
User=pi
ExecStartPre=/bin/sleep 5
ExecStart=/bin/bash -lc "cd $INSTALL_DIR && python3 player.py"
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
SERVICE
    systemctl daemon-reload
    systemctl enable tailsmusic.service
    log "Service created and enabled. Start with: sudo systemctl start tailsmusic"
fi

info ""
info "--- Adding Pi user to necessary groups ---"
usermod -a -G audio pi 2>/dev/null || true
usermod -a -G input pi 2>/dev/null || true

log ""
log "======================================"
log "  TailsMusic setup complete!"
log "======================================"
echo ""
info "Next steps:"
echo "  1. Place .mp3 files in: $INSTALL_DIR/songs/"
echo "  2. Verify button codes: sudo evtest"
echo "     Then edit: $INSTALL_DIR/config.json"
echo "  3. Reboot: sudo reboot"
echo ""
info "If paired, TailsMusic will auto-connect to your headphones and start."
